"""Generador de mazos extendidos (≥2000 palabras) bilingües (ES/EN) de alta pureza terminológica."""

from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path("ddi_fw/data/extended")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# -----------------------------------------------------------------------------
# RECETA (Gastronomía, repostería, técnicas culinarias)
# -----------------------------------------------------------------------------
RECETA_CLAUSES_ES = [
    "Batir las claras de huevo a punto de nieve con una pizca de cremor tártaro durante seis minutos continuos hasta formar picos firmes y satinados.",
    "Tamizar la harina de trigo cuatro ceros junto con el polvo para hornear y el almidón de maíz en tres tandas para airear la mezcla y evitar grumos.",
    "Precalentar el horno convector a 175 grados Celsius y enmantecar prolijamente el molde desmontable antes de espolvorear con cacao amargo en polvo.",
    "Disolver la levadura seca prensada en leche entera tibia a 36 grados agregando una cucharada pequeña de miel y dejar reposar hasta que espume.",
    "Amasar la preparación sobre la mesada enharinada plegando sobre sí misma hasta obtener un bollo liso, sedoso y de textura perfectamente elástica.",
    "Dejar fermentar la masa en un cuenco aceitado cubierto con un paño limpio y húmedo en un rincón tibio hasta que duplique holgadamente su volumen.",
    "Saltear las chalotas finamente picadas en manteca clarificada a fuego suave hasta que queden transparentes y caramelizadas sin quemarse los bordes.",
    "Reducir el fondo oscuro de carne vacuna con vino tinto y hierbas frescas durante cuarenta minutos a hervor tenue espumando las impurezas.",
    "Cortar las zanahorias y el puerro en juliana uniforme para incorporar a la cocción del caldo aromático aromatizado con hojas de laurel y tomillo.",
    "Fundir el chocolate cobertura amargo a baño de María asegurando que el agua del recipiente inferior no toque jamás la base del cuenco superior.",
    "Templar el chocolate sobre la mesada de mármol realizando movimientos envolventes con espátula hasta bajar la temperatura a veintisiete grados.",
    "Remontar la temperatura del chocolate a treinta y un grados antes de verter en los moldes de bombones para lograr brillo y quiebre crujiente.",
    "Emulsionar las yemas frescas con vinagre de manzana y mostaza de Dijón vertiendo aceite de girasol en un hilo continuo y pausado.",
    "Desglasar la sartén caliente con oporto tras sellar el lomo de cerdo para desprender todos los jugos caramelizados pegados al fondo de cocción.",
    "Confitar los dientes de ajo pelados sumergidos en aceite de oliva extra virgen a setenta grados Celsius durante dos horas enteras.",
    "Blanquear los espárragos verdes en abundante agua hirviendo salada durante dos minutos y cortar la cocción inmediatamente en un baño de agua helada.",
    "Preparar un almíbar a punto bolita blanda hirviendo agua con azúcar blanco refinado hasta registrar exactamente ciento dieciocho grados en el termómetro.",
    "Mezclar la crema pastelera fría con crema de leche batida a medio punto para elaborar una crema diplomática ligera apta para rellenar milhojas.",
    "Hornear la masa quebrada a ciegas cubierta con papel manteca y legumbres secas durante quince minutos para evitar que el fondo se infle.",
    "Marinar los filetes de pescado blanco con jugo fresco de lima, cilantro picado, chile dulce y sal marina durante veinte minutos en frío.",
    "Escalfar las peras peladas en un almíbar especiado con anís estrellado, clavo de olor y canela en rama a fuego imperceptible hasta tiernizar.",
    "Dorar los granos de arroz carnaroli en aceite caliente antes de añadir el vino blanco seco para comenzar la elaboración del risotto cremoso.",
    "Incorporar caldo de verduras hirviendo cucharón a cucharón mientras se remueve continuamente con cuchara de madera para soltar el almidón.",
    "Mantecar el risotto fuera del fuego agregando manteca bien fría en cubos y queso parmesano rallado fino hasta emulsionar una textura fluida.",
    "Estirar la masa de hojaldre frío aplicando vueltas dobles y descansando en heladera entre cada pliegue para asegurar hojaldrado crocante.",
    "Hornear las barras de pan baguette con inyección de vapor de agua durante los primeros diez minutos para generar una corteza dorada y crujiente.",
    "Tostar semillas de sésamo y lino dorado en una sartén seca a fuego moderado moviendo constantemente para evitar que desprendan amargor.",
    "Rallar la cáscara de naranja dulce y limón evitando la parte blanca amarga para perfumar la masa del budín cítrico esponjoso.",
    "Rehidratar los hongos secos de pino en caldo caliente durante treinta minutos antes de colar el líquido por filtro de tela fina.",
    "Sellar la carne de ternera trozada a fuego muy vivo en una cacerola de hierro fundido para atrapar todos los jugos sabrosos en su interior.",
    "Cocinar el ragú a fuego bajo tapado durante tres horas agregando tomates perita triturados y una hoja fresca de romero aromático.",
    "Espolvorear con sal entrefina y pimienta negra recién molida sobre la superficie de las verduras asadas al horno de leña.",
    "Hidratar hojas de gelatina sin sabor en agua helada durante diez minutos y escurrir con las manos antes de fundir en la preparación tibia.",
    "Colar la mermelada tibia de frutos rojos a través de un tamiz metálico para eliminar las semillas pequeñas y lograr un coulis terso y brillante.",
    "Cocinar las papas enteras con piel en agua salada hasta que al pinchar con un cuchillo fino caigan por su propio peso sin romperse.",
    "Tamizar las papas calientes con prensa puré agregando manteca pomada, nuez moscada rallada fresca y leche entera recién hervida.",
    "Llevar la leche condensada a baño de María tapada con papel de aluminio durante tres horas para transformar lentamente en dulce de leche.",
    "Enfriar el merengue italiano batiendo a velocidad alta hasta que el bol de la batidora alcance temperatura ambiente y mantenga picos duros.",
    "Pintar la superficie de las empanadas criollas con huevo batido y una pizca de azúcar antes de hornear a temperatura máxima por doce minutos.",
    "Dorar cebollas cortadas en pluma con una pizca de bicarbonato de sodio a fuego lento hasta alcanzar caramelización profunda sin azúcares añadidos.",
    "Deshuesar los muslos de pollo conservando la piel intacta para rellenar con espinacas salteadas, piñones tostados y queso provolone estacionado.",
    "Hornear la masa sablée a ciento sesenta grados hasta que adquiera una tonalidad dorada tenue y una textura crocante que se deshaga al paladar.",
    "Hervir la pulpa fresca de maracuyá con azúcar mascabo durante doce minutos espumando constantemente para obtener una jalea densa y ácida.",
    "Batir la manteca pomada con azúcar impalpable tamizada hasta blanquear y lograr una crema suave ideal para cobertura de pasteles de boda.",
    "Infundir granos de café tostado partido en crema de leche caliente durante veinticuatro horas en heladera antes de colar y batir a punto chantilly.",
    "Macerar frutos secos y pasas de uva rubias en licor de amaretto y ron añejo durante una semana para elaborar el pan dulce artesanal navideño.",
    "Cocer al vapor piezas de salmón rosado con rodajas finas de jengibre fresco y cebolla de verdeo sobre canasta de bambú durante ocho minutos.",
    "Descorazonar las manzanas verdes y espolvorear con azúcar morena, canela molida y una nuez de manteca antes de asar al horno medio.",
    "Batir yemas de huevo con vino marsala dulce a baño de María hasta duplicar el volumen y formar un sabayón espeso y aterciopelado.",
    "Aromatizar el aceite de oliva suave macerando ramitas de romero fresco, granos de pimienta blanca y cáscara de pomelo durante quince días.",
    "Tamizar almidón de tapioca con fécula de mandioca para ligar salsas calientes otorgando un acabado transparente y libre de grumos indeseados.",
    "Hornear discos de merengue suizo a noventa grados durante dos horas enteras con la puerta del horno levemente entreabierta para secar sin dorar.",
    "Picar finamente hojas de albahaca fresca y dientes de ajo majados en mortero de piedra incorporando queso pecorino y piñones molidos.",
    "Verter el glaseado espejo brillante a treinta y dos grados sobre la mousse congelada para garantizar una cobertura lisa, uniforme y reflectante.",
    "Reposar el bizcochuelo recién horneado sobre una rejilla metálica para que el vapor escape por la base evitando que la miga se humedezca.",
]

RECETA_CLAUSES_EN = [
    "Whip the fresh egg whites with a pinch of cream of tartar on medium speed until soft peaks begin to form.",
    "Sift the unbleached all-purpose flour together with baking powder and fine sea salt twice to ensure uniform aeration.",
    "Preheat the convection oven to three hundred and fifty degrees Fahrenheit and line the baking sheet with silicone parchment paper.",
    "Proof active dry yeast in warm whole milk with raw cane sugar for ten minutes until a thick frothy head develops.",
    "Knead the bread dough vigorously on a wooden surface until it passes the translucent windowpane test without tearing apart.",
    "Cover the fermenting dough in a lightly oiled bowl with a damp linen towel and allow to double in bulk in a draft-free environment.",
    "Sweat finely minced shallots and crushed garlic cloves in clarified butter over gentle heat until fragrant, translucent, and sweet.",
    "Simmer the roasted beef stock with aromatic mirepoix and tomato paste for forty-five minutes, regularly skimming the floating foam.",
    "Slice ripe beefsteak tomatoes and crisp iceberg lettuce into thin wedges, dressing with extra virgin olive oil and sherry vinegar.",
    "Melt sixty-percent dark chocolate over a gentle double boiler without letting any steam or moisture enter the tempering basin.",
    "Table the molten couverture chocolate across cold granite slab using offset spatulas until crystallization thickens the glossy glaze.",
    "Reheat the tempered chocolate to eighty-eight degrees Fahrenheit to achieve ideal snap, sheen, and contraction during mould release.",
    "Whisk egg yolks rapidly with Dijon mustard, slowly drizzling sunflower oil in a micro-thin stream to build a silky emulsion.",
    "Deglaze the stainless steel skillet with dry white wine after searing pork tenderloins to dissolve fond into a pan sauce.",
    "Slowly poach fresh garlic cloves immersed in virgin olive oil at one hundred and sixty degrees Fahrenheit for two full hours.",
    "Blanch fresh green asparagus spears in salted boiling water for two minutes before shocking them into an ice water bath.",
    "Boil refined granulated sugar with filtered spring water until the candy thermometer registers two hundred and forty degrees Fahrenheit.",
    "Fold chilled vanilla pastry cream into lightly whipped heavy whipping cream to assemble a delicate diplomat filling for choux buns.",
    "Blind bake the sweet shortcrust pastry weighted with dried ceramic baking beans for fifteen minutes until pale golden and dry.",
    "Cure raw sea bass fillets with freshly squeezed lime juice, julienned red onion, sea salt, and habanero slices in the chiller.",
    "Poach peeled Bosc pears in sweet riesling wine infused with cinnamon bark, whole cloves, and star anise until fork tender.",
    "Toast arborio rice grains in heated olive oil until edges become pearlescent before splashing dry vermouth into the heavy saucepan.",
    "Ladle boiling chicken broth into the simmering rice one scoop at a time, stirring constantly to release rich amylopectin starches.",
    "Finish the creamy risotto off the flame by vigorously beating in chilled butter cubes and freshly grated aged Parmigiano cheese.",
    "Laminate the butter dough block through three consecutive envelope turns, chilling between each fold to keep butter layers distinct.",
    "Inject steam into the bread baking chamber during the first ten minutes to gelatinize starch and produce a blistered crust.",
    "Dry-toast white sesame seeds and cumin seeds in a hot skillet, shaking continuously until they release nutty aromas and crackle.",
    "Finely zest unwaxed Meyer lemons and Valencia oranges, taking care to exclude bitter white pith from the citrus sponge cake.",
    "Steep dehydrated wild porcini mushrooms in boiling mineral water for half an hour, filtering the earthy liqueur through fine cheesecloth.",
    "Sear prime ribeye steak over blistering cast iron grates to achieve a deep mahogany Maillard crust without overcooking the center.",
    "Simmer traditional beef ragu over low heat for four hours with crushed San Marzano tomatoes, bay leaves, and cracked black pepper.",
    "Season roasted root vegetables generously with flaky Maldon salt and freshly crushed rainbow peppercorns right before plating.",
    "Bloom leaf gelatin sheets in ice cold water for ten minutes, gently squeezing out excess liquid before stirring into warm cream.",
    "Pass fresh raspberry puree through a fine mesh conical strainer to extract tiny seeds and yield a velvety smooth dessert coulis.",
    "Boil Yukon gold potatoes with skins intact in generously salted water until tender enough to pierce effortlessly with a pairing knife.",
    "Rice hot steamed potatoes directly through a mechanical ricer, incorporating salted European butter and warm whole milk.",
    "Bake sweetened condensed milk in a water bath covered with heavy foil for three hours to convert into thick golden caramel spread.",
    "Cool the Italian meringue at maximum whipping speed until glossy, stiff, and the exterior of the mixing bowl cools completely.",
    "Brush brioche pastry tops with whole egg wash and a sprinkle of coarse demerara sugar before baking at high temperature.",
    "Caramelize sliced yellow onions low and slow in duck fat for sixty minutes until deep amber, jammy, and intensely rich in natural sugars.",
    "Truss the whole roasting chicken tightly with unbleached butcher twine to promote even heat circulation through both breast and thighs.",
    "Whisk cold butter cubes into reduced balsamic vinegar off the flame to mount a velvet sauce for pan-roasted duck breast.",
    "Rest seared venison steaks on a warm wooden carving board for ten minutes to permit internal juices to redistribute evenly.",
    "Submerge duck legs in seasoned rendered goose fat with fresh rosemary sprigs, slow-cooking at two hundred degrees Fahrenheit for five hours.",
    "Infuse whole milk with split Tahitian vanilla pods and crushed cardamom pods, scalding gently before tempering into egg yolk custard.",
    "Dust chilled chocolate truffles with alkalized Dutch cocoa powder using a fine wire sifter to create a matte, bittersweet outer coating.",
    "Steam fresh mussels in dry hard cider with chopped leeks, cracked fennel seeds, and heavy cream until all bivalve shells spring open.",
    "Shave raw baby artichoke hearts on a Japanese mandoline, tossing immediately in cold lemon juice water to prevent oxidative discoloration.",
    "Churn the chilled custard base in a pre-frozen ice cream maker for twenty-five minutes until firm, velvety, and properly overrun.",
    "Bake sourdough batards inside a preheated cast iron Dutch oven with lid on for twenty minutes before venting to darken the blistered ear.",
    "Clarify raw chicken stock by gently simmering with a raft of whipped egg whites, ground poultry, and minced root aromatics.",
    "Pipe choux pastry dough into three-inch mounds onto baking sheets, dusting with confectioner sugar before baking into airy gougeres.",
    "Steep loose leaf Earl Grey black tea in hot scalded cream for fifteen minutes to infuse floral bergamot notes into ganache.",
    "Press salted cabbage shreds tightly into stoneware crock fermentation pots, keeping submerged under brine until lactic acidity develops.",
    "Warm maple syrup with pure bourbon whiskey and toasted pecan pieces to ladle hot over freshly churned vanilla bean gelato.",
]

# -----------------------------------------------------------------------------
# PYTHON (Lenguaje de programación, estructuras, runtime, typing, concurrencia)
# -----------------------------------------------------------------------------
PYTHON_CLAUSES_ES = [
    "En Python una lista es una secuencia mutable cuyos elementos se acceden por índice entero y permite métodos como append y extend.",
    "El bucle for itera sobre cualquier objeto iterable consumiendo elementos sucesivamente mediante el protocolo iterador nativo.",
    "Las funciones se definen con la palabra reservada def y pueden retornar múltiples valores empaquetados en una tupla inmutable.",
    "Las excepciones se capturan mediante bloques try except y opcionalmente un bloque finally que asegura la liberación de recursos.",
    "Los diccionarios almacenan pares clave valor implementando tablas hash eficientes con búsqueda y modificación en tiempo constante promedio.",
    "Un conjunto set es una colección desordenada de elementos únicos que soporta operaciones matemáticas como unión, intersección y diferencia.",
    "Las comprensiones de listas permiten transformar colecciones de manera concisa mediante expresiones evaluadas dentro de corchetes cuadrados.",
    "Los generadores producen valores perezosamente utilizando la sentencia yield preservando el estado de ejecución de la función local.",
    "El administrador de contexto implementa el protocolo enter y exit para garantizar la inicialización y cierre correcto de archivos y sockets.",
    "La biblioteca estándar incluye el módulo asyncio para ejecutar corrutinas concurrentes sobre un bucle de eventos asíncrono no bloqueante.",
    "Las clases admiten herencia simple y múltiple calculando el orden de resolución de métodos mediante el algoritmo canónico C3 linearization.",
    "El recolector de basura de CPython emplea conteo de referencias combinado con un recolector generacional para detectar ciclos cíclicos inalcanzables.",
    "Los decoradores son funciones de orden superior que reciben otra función como argumento y devuelven un envoltorio con comportamiento extendido.",
    "El módulo inspect permite inspeccionar objetos en tiempo de ejecución extrayendo código fuente, signaturas de funciones y cuadros de pila.",
    "Las tuplas nombradas del módulo collections proporcionan campos accesibles por nombre manteniendo la inmutabilidad de la tupla estándar.",
    "El módulo dataclasses simplifica la definición de clases de datos generando automáticamente métodos constructores init y comparadores de igualdad.",
    "El operador morsa permite asignar valores a variables dentro de expresiones booleanas reduciendo evaluaciones redundantes en condicionales complejos.",
    "Los descriptores son objetos con métodos get, set o delete que gestionan el acceso a atributos de instancias en otras clases.",
    "El módulo typing introduce anotaciones de tipos estáticos analizadas por verificadores como mypy para garantizar corrección en compilación preliminar.",
    "Las cadenas de texto formateadas permiten incrustar expresiones arbitrarias dentro de literales de texto precedidos por la letra f.",
    "El módulo multiprocessing sortea las restricciones del bloqueo global de intérprete spawning procesos independientes con memoria propia.",
    "El paquete collections provee la clase defaultdict que inicializa automáticamente claves inexistentes mediante una función fábrica provista.",
    "Las variables de alcance no local se declaran con nonlocal para modificar enlaces en ámbitos circundantes dentro de clausuras anidadas.",
    "El módulo functools expone la función lru_cache para memorizar automáticamente llamadas deterministas optimizando funciones recursivas costosas.",
    "El analizador sintáctico de Python compila código fuente a un árbol de sintaxis abstracta antes de transformarlo en secuencias de bytecode.",
    "La función incorporada zip combina múltiples secuencias en paralelo generando tuplas hasta agotar el iterable más corto proporcionado.",
    "El decorador classmethod transforma una función en un método ligado a la clase receptora en lugar de ligarse a una instancia particular.",
    "El decorador staticmethod declara métodos utilitarios dentro del espacio de nombres de la clase sin recibir referencias explícitas a self.",
    "El módulo itertools ofrece funciones eficientes para manipulación combinatoria como product, permutations, combinations y count infinito.",
    "El operador de desempaquetado de argumentos asterisco descompone listas y tuplas posicionales en invocaciones de funciones complejas.",
    "El operador de doble asterisco desempaqueta diccionarios asignando pares clave valor a parámetros con nombre en funciones definidas.",
    "El protocolo de ordenamiento timsort híbrido combina insertion sort y merge sort para ofrecer estabilidad y rendimiento óptimo en datos reales.",
    "El módulo queue provee colas sincronizadas y seguras para intercambio de mensajes entre hilos de ejecución concurrentes en memoria.",
    "Las ranuras slots restringen la creación de atributos dinámicos reduciendo drásticamente el consumo de memoria en millones de instancias.",
    "El bucle while repite la ejecución de un bloque de código mientras una condición booleana permanezca evaluada como verdadera.",
    "La instrucción raise propaga una instancia de excepción personalizada interrumpiendo el flujo de control hacia los manejadores superiores.",
    "El método dunder str define la representación textual legible para usuarios mientras que repr define la representación técnica sin ambigüedad.",
    "Las metaclases heredan de type y permiten interceptar la construcción de nuevas clases sobreescribiendo los métodos new e init.",
    "El módulo threading proporciona primitivas de sincronización concurrente como candados Lock, semáforos y variables de condición Condition.",
    "La función map aplica una función unaria sobre cada elemento de una secuencia devolviendo un iterador perezoso con los resultados transformados.",
    "El módulo dis desensambla objetos de código Python produciendo un volcado legible de nemónicos de bytecode interpretados por la máquina virtual.",
    "La biblioteca weakref permite mantener referencias débiles a objetos mutables sin incrementar el contador de referencias impidiendo fugas de memoria.",
    "El módulo contextvars proporciona almacenamiento local para tareas asíncronas preservando el contexto a través de corrutinas concurrentes concurrentes.",
    "La construcción match case introducida en Python introduce pattern matching estructural permitiendo destructuring de secuencias y mapeos complejos.",
    "El módulo operator expone funciones convenientes equivalentes a operadores aritméticos y lógicos intrínsecos como add, mul y itemgetter.",
    "El módulo array implementa matrices homogéneas eficientes que almacenan tipos de datos primitivos de C contiguos en memoria física.",
    "La función bisect localiza puntos de inserción binaria sobre secuencias ordenadas manteniendo el orden de clasificación en tiempo logarítmico.",
    "El módulo gc expone funciones de control directo sobre el recolector de basura cíclico permitiendo pausar, reanudar o forzar pasadas de recolección.",
    "El decorador property convierte métodos de instancia en atributos de solo lectura o lectura y escritura con validación personalizada.",
    "El módulo copy proporciona la función deepcopy para duplicar recursivamente estructuras de datos anidadas rompiendo referencias compartidas.",
    "La función compile compila cadenas de texto fuente en objetos de código ejecutables por las funciones nativas eval o exec.",
    "El módulo timeit permite medir tiempos de ejecución con precisión de microsegundos ejecutando fragmentos de código millones de repeticiones.",
    "El protocolo async with gestiona el ciclo de vida de administradores de contexto asíncronos implementando aenter y aexit en corrutinas.",
    "El método dunder hash devuelve un entero de sesenta y cuatro bits que indexa objetos inmutables dentro de colecciones basadas en hash.",
    "El módulo enum define enumeraciones fuertemente tipadas con soporte para miembros únicos e iterables mediante la clase base Enum.",
]

PYTHON_CLAUSES_EN = [
    "In Python a list represents a mutable sequence indexed by integers supporting methods such as append, insert, pop, and extend.",
    "The for statement iterates across iterable items consuming elements through the standard iterator protocol using next and iter.",
    "Functions are defined using the def keyword and may return multiple unpacked values structured as an immutable heterogeneous tuple.",
    "Exceptions are handled using structured try and except blocks with an optional finally clause ensuring reliable cleanup of resources.",
    "Dictionaries map unique hashable keys to arbitrary values providing efficient amortized constant time lookups and modifications.",
    "A set represents an unordered mutable collection of unique items supporting mathematical operations such as union, intersection, and difference.",
    "List comprehensions provide a concise declarative syntax for mapping and filtering elements into fresh sequence allocations.",
    "Generators emit stream values lazily using the yield statement, suspending execution frame state until the next iteration occurs.",
    "Context managers implement the enter and exit dunder methods to guarantee predictable initialization and teardown of socket descriptors.",
    "The standard library provides the asyncio module to schedule and execute concurrent coroutines over a non-blocking asynchronous event loop.",
    "Classes support both single and multiple inheritance resolving method lookup conflicts via the deterministic C3 linearization algorithm.",
    "The CPython memory runtime couples deterministic reference counting with an auxiliary generational cyclic garbage collector.",
    "Decorators operate as higher order functions accepting callable objects and returning wrapped callables with augmented runtime behaviors.",
    "The inspect module allows dynamic runtime introspection of frame stacks, live source code, class hierarchies, and signature parameters.",
    "Named tuples from collections deliver lightweight immutable record structures with named attribute access alongside tuple indexability.",
    "Dataclasses automatically synthesize boilerplates such as init, repr, eq, and hash methods based on class level type annotations.",
    "The walrus operator assigns expressions to variables within enclosing conditional blocks to eliminate repeated nested calculations.",
    "Descriptors are objects implementing get, set, or delete methods to customize attribute lookup mechanics across class instances.",
    "The typing module provides static type hint constructors evaluated by static linters like mypy to catch inconsistencies ahead of runtime.",
    "Formatted string literals enable interpolation of arbitrary runtime expressions embedded directly within quotation prefixes.",
    "The multiprocessing package spawns independent interpreter processes bypassing global interpreter lock contention across multiple cores.",
    "The collections defaultdict populates absent keys automatically whenever queried by delegating to a user supplied default factory.",
    "The nonlocal keyword rebinds variable identifiers located in outer non-global enclosing scopes during nested closure executions.",
    "The functools lru cache wraps deterministic callables with an in-memory dictionary cache to accelerate expensive recursive evaluations.",
    "The Python compiler compiles raw source text into abstract syntax trees before generating compact bytecode instructions for evaluation.",
    "The built-in zip function pairs corresponding elements from multiple iterables sequentially until the shortest input sequence terminates.",
    "The classmethod decorator transforms instance functions into methods bound directly to the declaring class object rather than instances.",
    "The staticmethod decorator defines self-contained utility routines inside a class namespace without injecting implicit instance bindings.",
    "The itertools module implements memory efficient combinatorial tools including Cartesian product, permutations, combinations, and cycle.",
    "The star unpacking operator unpacks iterable collections into distinct positional arguments during dynamic function dispatch invocations.",
    "The double star operator unpacks dictionary key value pairs into keyword parameters during dynamic callable invocation sequences.",
    "The timsort sorting algorithm combines adaptive insertion sort with merge sort passes to deliver optimal efficiency on partially ordered inputs.",
    "The thread-safe queue module coordinates synchronized task handoffs between concurrent worker threads without manual lock arbitration.",
    "The slots class declaration suppresses dynamic instance dictionary creation, substantially shrinking memory overhead across large fleets.",
    "The while loop evaluates a control predicate before every iteration, repeating loop body execution until the expression yields false.",
    "The raise keyword propagates custom exception instances through active call frames until intercepted by matching except clauses.",
    "The str dunder method yields human readable string representations while repr returns unambiguous technical diagnostic strings.",
    "Metaclasses inherit from type and intercept class construction sequences by overriding class allocation new and initialization init hooks.",
    "The threading module coordinates multi-threaded concurrency using synchronization primitives including Lock, Semaphore, and Event.",
    "The built-in map function applies a unary transformation across sequence iterables, streaming resulting values lazily on demand.",
    "The dis module disassembles Python code objects into readable instructions revealing bytecode opcodes executed by the virtual machine.",
    "The weakref module provides weak references allowing garbage collection of referenced objects without artificially elevating reference counters.",
    "Contextvars module supplies context variables holding state isolation for asynchronous coroutines running inside shared event loops.",
    "Structural pattern matching with match and case statements enables expressive destructuring of complex dictionary and tuple payloads.",
    "The operator module exports functional wrappers around standard arithmetic and comparison operations such as attrgetter and itemgetter.",
    "The array module defines space efficient homogeneous memory sequences storing contiguous C primitives without python object boxing.",
    "The bisect module performs binary searching across sorted lists to calculate insertion boundaries maintaining sorted order in logarithmic time.",
    "The gc module grants program access to the cyclic garbage collector providing interfaces to inspect uncollected cyclic references.",
    "The property decorator exposes getter, setter, and deleter descriptors that encapsulate instance attributes behind transparent method calls.",
    "The copy module provides copy and deepcopy functions to create shallow or fully recursive copies of arbitrary nested python data structures.",
    "The builtin compile function parses source strings into executable code objects evaluated dynamically by eval or exec functions.",
    "The timeit module measures microsecond execution times of small code snippets by repeating executions across isolated benchmark loops.",
    "The async with statement manages asynchronous context managers executing aenter and aexit coroutines inside event loop schedules.",
    "The hash dunder method returns an integer used to look up immutable keys within dictionary hash tables and set collections.",
    "The enum module defines enumerated constants grouped as distinct typed members via the Enum base class architecture.",
]

# -----------------------------------------------------------------------------
# LEGAL (Contratos, licencias, arbitraje, propiedad intelectual, jurisdicción)
# -----------------------------------------------------------------------------
LEGAL_CLAUSES_ES = [
    "El presente contrato de prestación de servicios profesionales se celebra entre las partes signatarias con plena capacidad jurídica para obligarse.",
    "Las partes convienen expresamente que cualquier controversia derivada del cumplimiento o interpretación será resuelta mediante arbitraje vinculante.",
    "El contratista se obliga a mantener estricta confidencialidad respecto a toda información técnica, comercial o financiera recibida del cliente.",
    "La vigencia de las obligaciones de secreto y confidencialidad subsistirá durante un período ininterrumpido de cinco años tras la rescisión contractual.",
    "Queda expresamente prohibida la cesión total o parcial de los derechos u obligaciones emergentes del presente acuerdo sin consentimiento previo por escrito.",
    "El cliente abonará los honorarios devengados dentro de los treinta días corridos contados a partir de la recepción formal de la factura correspondiente.",
    "La mora en el cumplimiento de las obligaciones dinerarias operará de pleno derecho por el mero vencimiento de los plazos sin necesidad de interpelación.",
    "El incumplimiento material de cualquiera de las cláusulas esenciales facultará a la parte cumplidora a resolver el vínculo mediante notificación fehaciente.",
    "La parte afectada por un supuesto de fuerza mayor o caso fortuito quedará eximida de responsabilidad durante el lapso que persista el impedimento.",
    "El contratista declara y garantiza que todos los entregables desarrollados constituyen obras originales y no infringen derechos de propiedad ajenos.",
    "Todos los derechos patrimoniales de autor sobre las creaciones resultantes se considerarán transferidos al cliente en forma exclusiva y definitiva.",
    "El contratista mantendrá indemne al cliente frente a cualquier reclamo, demanda o acción judicial promovida por terceros fundada en infracción de marcas.",
    "La invalidez o nulidad de alguna de las disposiciones del presente instrumento no afectará la validez y exigibilidad de las restantes estipulaciones.",
    "Las notificaciones judiciales o extrajudiciales serán cursadas por medio fehaciente a los domicilios especiales constituidos en el encabezado.",
    "Las partes se someten a la jurisdicción exclusiva de los tribunales ordinarios competentes renunciando expresamente a cualquier otro fuero que pudiere corresponder.",
    "El contratista actuará en todo momento como un profesional independiente sin que exista relación de subordinación jurídica o dependencia laboral alguna.",
    "La renuncia por alguna de las partes al ejercicio de una acción judicial derivada de un incumplimiento no implicará renuncia a reclamar incumplimientos futuros.",
    "Cualquier modificación o enmienda a los términos estipulados en el presente acuerdo requerirá de adenda escrita debidamente suscripta por apoderados.",
    "El presente instrumento constituye el acuerdo íntegro y definitivo entre las partes, derogando cualesquiera entendimientos preliminares previos.",
    "Las partes acuerdan que las firmas digitales o electrónicas estampadas en el presente gozarán de idéntica validez jurídica que las firmas ológrafas.",
    "El contratista responderá por los daños y perjuicios directos ocasionados al cliente que sean consecuencia inmediata y comprobable de dolo o culpa grave.",
    "La indemnización por daños emergentes pactada bajo el presente contrato no comprenderá bajo ninguna circunstancia el lucro cesante ni daños punitivos.",
    "El cliente podrá auditar periódicamente los libros contables y registros vinculados al cumplimiento de los hitos de entrega previa notificación razonable.",
    "Los tributos, tasas y contribuciones que graven el ejercicio de la actividad profesional correrán por cuenta exclusiva de la parte designada por ley.",
    "En caso de rescisión anticipada sin causa imputable, el cliente abonará exclusivamente los servicios efectivamente prestados hasta la fecha de cese.",
    "El contratista se compromete a devolver de inmediato todo material sensible, soporte magnético o documentación confidencial en su poder.",
    "Las cláusulas relativas a indemnidad, confidencialidad, propiedad intelectual y resolución de disputas sobrevivirán a la expiración del contrato.",
    "El plazo pactado para la subsanación de cualquier intimación por incumplimiento será de quince días hábiles a computar desde la recepción fehaciente.",
    "El contratista declara contar con las habilitaciones administrativas, matrículas profesionales y seguros de responsabilidad civil pertinentes.",
    "Ninguna de las partes incurrirá en mora si el retraso en la prestación obedece a demoras injustificadas en las aprobaciones debidas por la contraparte.",
    "La suscripción del presente documento implica la plena aceptación de los anexos técnicos que forman parte integrante e inescindible del convenio.",
    "El retraso en el pago devengará un interés compensatorio y punitorio equivalente a la tasa activa fijada por la autoridad bancaria nacional.",
    "La parte perjudicada por revelación indebida de secretos industriales tendrá derecho a solicitar medidas cautelares urgentes sin fianza previa.",
    "El contratista no podrá subcontratar la ejecución material de las tareas comprometidas sin autorización escrita y expresa emanada del comitente.",
    "Ambas partes declaran bajo juramento que sus respectivos firmantes ostentan facultades representativas suficientes que no les han sido revocadas ni limitadas.",
    "Las obligaciones de no competencia comercial mantendrán plena vigencia dentro del territorio geográfico pactado por un lapso no inferior a dos años.",
    "Los costos y costas judiciales derivados de litigios necesarios para exigir el cobro forzado de sumas adeudadas serán asumidos por la parte deudora.",
    "El presente contrato se redacta en dos ejemplares de un mismo tenor y a un solo efecto, recibiendo cada parte signataria su copia correspondiente.",
    "Las partes acuerdan interpretar armónicamente las cláusulas atendiendo a la verdadera intención de los contratantes y a la buena fe comercial.",
    "La quiebra, liquidación o concurso preventivo de acreedores de cualquiera de las partes habilitará la resolución inmediata de pleno derecho.",
    "El contratista se obliga a cumplir rigurosamente con todas las normas vigentes en materia de seguridad social y previsión laboral respecto a sus dependientes.",
    "Las partes declaran que las penalidades pactadas en la cláusula penal representan una liquidación previa, razonable y equitativa de los perjuicios estimados.",
    "La omisión de exigir el cumplimiento estricto de cualquier término no constituirá una novación de las obligaciones contractualmente asumidas.",
    "El cliente mantendrá indemne al contratista frente a reclamaciones derivadas de datos o materiales suministrados directamente por el cliente que infrinjan derechos.",
    "Todo conflicto derivado de la titularidad de patentes de invención será sometido a peritaje técnico vinculante designado por el centro arbitral.",
    "El presente contrato se regirá e interpretará de conformidad con las leyes comerciales y civiles aplicables en la jurisdicción acordada.",
    "Las partes convienen fijar domicilio legal en las direcciones consignadas donde tendrán plena validez todas las comunicaciones y emplazamientos cursados.",
    "El contrato entrará en vigencia a partir de la fecha de suscripción de la última de las firmas requeridas en el pliego contractual.",
    "El contratista garantiza que los servicios serán ejecutados con los más altos estándares profesionales de diligencia y pericia técnica exigibles.",
    "Cualquier cesión de posición contractual efectuada en contravención a lo aquí previsto será considerada nula y sin ningún efecto legal entre partes.",
    "Las sumas retenidas en concepto de fondo de reparo serán reintegradas transcurridos noventa días desde la recepción provisoria satisfactoria.",
    "El cliente se reserva el derecho de rechazar entregables que no satisfagan los criterios objetivos de aceptación plasmados en los anexos.",
    "El acuerdo no confiere ningún beneficio, derecho o acción a terceros ajenos que no revistan la calidad de partes contratantes legítimas.",
    "En caso de contradicción entre las cláusulas del cuerpo principal y los términos de las órdenes de compra, prevalecerá el contrato marco.",
    "Las partes se comprometen a negociar de buena fe cualquier adaptación contractual requerida por modificaciones sobrevinientes en el marco regulatorio.",
]

LEGAL_CLAUSES_EN = [
    "This master professional services agreement is executed between the undersigned corporate entities with full legal capacity to contract.",
    "The contracting parties mutually agree that any legal dispute arising from this contract shall be settled by binding confidential arbitration.",
    "The independent contractor agrees to hold in strictest confidence all proprietary, financial, and technical documentation disclosed by the client.",
    "The restrictive covenants regarding confidentiality and trade secrets shall endure for five consecutive years following agreement expiration.",
    "Neither party may assign, delegate, or transfer its rights or duties under this agreement without prior written authorization from the other party.",
    "Client covenants to remit payment for approved professional fees within thirty calendar days from receipt of an undisputed itemized invoice.",
    "Any default in monetary obligations shall trigger automatic default interest penalties without requiring prior formal demand or judicial notice.",
    "Material breach of any essential contractual condition entitles the aggrieved non-breaching party to terminate the covenant upon written notice.",
    "Neither contracting party shall be held legally liable for delay in performance caused by unforeseeable events of force majeure or government decrees.",
    "Contractor warrants and represents that all deliverable materials are entirely original and do not infringe upon any third-party intellectual property.",
    "All worldwide copyright, patent rights, and proprietary rights in the bespoke deliverables are hereby assigned exclusively to the corporate client.",
    "Contractor shall defend, indemnify, and hold harmless the client against any third-party claims, liabilities, or losses alleging patent infringement.",
    "If any clause or provision of this contract is held invalid or unenforceable by a competent tribunal, the remainder shall continue in full force.",
    "Formal legal notices must be delivered in writing via certified mail with recorded delivery to the registered principal offices specified herein.",
    "The parties submit exclusively to the personal jurisdiction and venue of the federal and state courts located within the state of Delaware.",
    "Contractor performs all duties as an independent contractor, and nothing herein shall create an employer-employee or agency relationship.",
    "Failure or delay by either party in exercising any statutory or contractual remedy shall not operate as an overarching waiver of such rights.",
    "No amendment, addendum, or variation of this contractual document shall take legal effect unless executed in written instruments signed by officers.",
    "This executed document embodies the entire agreement between the parties superseding all prior oral negotiations, memoranda, or proposals.",
    "The parties confirm that counterpart signatures exchanged by authenticated digital or electronic means shall constitute legally binding originals.",
    "Contractor liability for direct damages arising out of gross negligence or willful misconduct shall be capped at total fees paid under this agreement.",
    "Under no circumstances shall either contracting party be held liable for indirect, incidental, consequential, punitive, or lost profit damages.",
    "Client reserves the audit right to inspect operational logs and billing records relevant to deliverable milestones upon reasonable advance notice.",
    "All statutory corporate taxes, income withholdings, and commercial levies applicable to service fees shall be satisfied by the statutory taxpayer.",
    "In the event of termination for convenience, client shall tender compensation solely for validated services performed up to the termination date.",
    "Upon expiration or cancellation of this covenant, contractor shall immediately return or securely destroy all confidential records and media.",
    "Survival of legal covenants: provisions governing indemnification, confidentiality, dispute resolution, and governing law shall survive termination.",
    "The contractual cure period for any remediable default shall be fifteen consecutive business days following receipt of written cure demand.",
    "Contractor certifies maintenance of comprehensive commercial general liability insurance, professional indemnity coverage, and regulatory licenses.",
    "Neither party shall be in breach where delay in project milestone execution is attributable to unjustified withholding of client approvals.",
    "The execution of this master contract incorporates all appended schedules, exhibits, and technical statements of work by express reference.",
    "Past due balances shall accrue compounded interest at the rate of one and one-half percent per month or the statutory legal maximum permitted.",
    "The non-breaching party shall be entitled to seek immediate injunctive relief and equitable decrees to restrain unauthorized trade secret disclosure.",
    "Contractor shall not subcontract the core execution of milestone duties to third-party vendors without express prior written client consent.",
    "The authorized signatories expressly warrant that they possess corporate power and authorized board delegations to execute this binding contract.",
    "Non-solicitation covenants prohibiting the active recruitment of client engineering or managerial personnel shall survive for twenty-four months.",
    "In any contentious proceeding brought to enforce unpaid fee obligations, the prevailing litigant shall recover reasonable attorney fees and costs.",
    "This agreement is executed in duplicate identical counterparts, each of which shall be deemed an authentic original binding both signing parties.",
    "The contractual provisions shall be construed reasonably in accordance with mutual good faith dealing and customary commercial business practices.",
    "The filing of voluntary bankruptcy petitions or insolvency proceedings by either contracting party shall authorize instantaneous contract termination.",
    "Contractor warrants compliance with applicable anti-corruption statutes including the Foreign Corrupt Practices Act and statutory labor standards.",
    "Liquidated damages specified herein represent a genuine pre-estimate of loss and not a contractual penalty intended to deter lawful termination.",
    "Waiver of jury trial: each contracting party knowingly, voluntarily, and irrevocably waives any constitutional right to trial by jury in disputes.",
    "Client shall indemnify and hold contractor harmless against liabilities arising out of client-supplied specifications that infringe proprietary rights.",
    "Any technological patent dispute arising under this agreement shall be submitted to binding expert appraisal administered by the arbitration institute.",
    "This contract shall be construed, interpreted, and governed under the substantive commercial laws of the chosen governing jurisdiction.",
    "Formal process service and notices delivered to designated legal addresses shall constitute sufficient service for all evidentiary purposes.",
    "This agreement shall take legal effect immediately upon the date of mutual execution by authorized executive signatories of both corporations.",
    "Contractor represents that contractual milestone services shall be executed with ordinary professional care, diligence, and customary skill.",
    "Any purported assignment or delegation executed in violation of the anti-assignment provisions shall be void ab initio and unenforceable.",
    "Retainage deductions withheld by client shall be released within ninety days following issuance of the final certificate of milestone completion.",
    "Client retains the contractual right to reject deliverable items failing to satisfy objective verification criteria enumerated in work schedules.",
    "Nothing herein express or implied is intended or shall be construed to confer upon any third party any statutory rights or causes of action.",
    "In the event of irreconcilable conflict between terms of this master contract and individual purchase orders, master contract terms prevail.",
    "The parties agree to renegotiate in good faith contractual provisions rendered obsolete or unlawful by subsequent governmental regulatory shifts.",
]

# -----------------------------------------------------------------------------
# MEDICINA (Medicina clínica, farmacología y fisiopatología)
# -----------------------------------------------------------------------------
MEDICINA_CLAUSES_ES = [
    "La administración intravenosa de fibrinolíticos específicos en infarto agudo de miocardio reduce la mortalidad coronaria precoz en pacientes hospitalizados.",
    "El análisis nosológico de la meningitis bacteriana aguda requiere punción lumbar urgente con estudio citoquímico y microbiológico del líquido cefalorraquídeo purulento.",
    "La farmacocinética de los aminoglucósidos parenterales presenta escasa permeabilidad digestiva y una eliminación urinaria predominante por filtración glomerular renal.",
    "La cetoacidosis diabética descompensada cursa con deshidratación hídrica severa, acidosis metabólica con anión gap ensanchado y presencia abundante de cetoácidos.",
    "El abordaje quirúrgico reconstructivo del aneurisma aórtico abdominal infrarrenal previene la rotura vascular mediante implante de endoprótesis vascular flexible.",
    "La insuficiencia cardíaca congestiva con fracción de eyección deprimida mejora el pronóstico clínico con inhibidores selectivos del cotransportador renal.",
    "El shock séptico distributivo refractario a resucitación hidroelectrolítica requiere soporte vasopresor precoz con noradrenalina para sostener la perfusión tisular sistémica.",
    "La biopsia hepática percutánea ecoguiada permite evaluar con rigor histológico el grado de necroinflamación y el estadio de fibrosis avanzada.",
    "La videoendoscopia digestiva alta corrobora la etiología de la hemorragia gastrointestinal y posibilita aplicar hemostasia endoscópica mecánica o esclerosante.",
    "La elevación persistente de troponinas cardíacas ultrasensibles orienta el diagnóstico certero de injuria miocárdica aguda en el síndrome coronario.",
    "El trasplante alogénico de precursores hematopoyéticos erradica la clona leucémica residual mediante acondicionamiento mieloablativo e inmunidad injerto contra leucemia.",
    "La ventilación mecánica invasiva con parámetros de protección alveolar en distrés respiratorio agudo emplea volumen corriente bajo y presión teleespiratoria.",
    "La hemodiálisis extracorpórea depura toxinas urémicas acumuladas y remueve el excedente hídrico intravascular en la uremia terminal avanzada.",
    "La preeclampsia atípica cursa con hipertensión arterial severa, proteinuria patológica cuantificada y signos analíticos evidentes de disfunción endotelial materna.",
    "El tratamiento oncológico adyuvante con esquemas quimioterápicos basados en sales de platino prolonga la sobrevida global en carcinomas pulmonares.",
    "La punción aspirativa con aguja fina de nódulos tiroideos guiada por ecografía distingue neoplasias malignas según criterios citopatológicos estandarizados.",
    "El bloqueo inmunológico del receptor soluble de interleucina seis atenúa la cascada hiperinflamatoria sistémica en patologías autoinmunes graves.",
    "La trombectomía endovascular percutánea combinada con fibrinólisis mejora la recuperación funcional neurológica en el infarto cerebral isquémico agudo.",
    "La monitorización continua de la presión intracraneana en traumatismo encefalocraneano severo guía la osmoterapia para prevenir herniación cerebral irreversible.",
    "El tratamiento empírico inicial de la neumonía bacteriana adquirida en la comunidad combina betalactámicos bactericidas con macrólidos orales seleccionados.",
    "La detección serológica de autoanticuerpos antinucleares y anti-ADN nativo de doble cadena fundamenta el diagnóstico serológico del lupus eritematoso sistémico.",
    "La colecistectomía laparoscópica reglada de la vesícula biliar litiásica disminuye las complicaciones de pared y acelera la recuperación postoperatoria.",
    "La ecocardiografía Doppler transtorácica cuantifica la severidad hemodinámica de la estenosis aórtica calculando el orificio valvular efectivo funcional.",
    "El reemplazo hormonal sustitutivo con levotiroxina sódica sintética normaliza los niveles plasmáticos basales de tirotropina en hipotiroidismo primario.",
    "La laparotomía exploradora de urgencia está formalmente indicada ante peritonitis purulenta secundaria a perforación de víscera hueca intraabdominal.",
    "La fisiopatología del shock cardiogénico involucra un colapso brusco del gasto sistólico ventricular con hipoperfusión celular periférica generalizada.",
    "La profilaxis endoscópica primaria del sangrado variceal esofágico en hepatopatía cirrótica incluye ligadura elástica con bandas de goma hemostáticas.",
    "La citometría de flujo multiparamétrica identifica inmunofenotipos celulares patológicos esenciales para tipificar leucemias agudas y linfomas no hodgkinianos.",
    "El control farmacológico de la hipertensión arterial con bloqueantes cálcicos dihidropiridínicos induce vasodilatación periférica por relajación miocítica arteriolar.",
    "La neuroimagen por resonancia magnética con quelato de gadolinio evidencia lesiones desmielinizantes hiperintensas encefalomedulares en esclerosis múltiple remitente recurrente.",
    "La resucitación hidroelectrolítica vigorosa con soluciones cristaloides isotónicas amortigua la necrosis pancreática y el fracaso multiorgánico en pancreatitis.",
    "El toracostomía con tubo pleural subacuático desobstruye el neumotórax hipertensivo y reinstaura la presión negativa fisiológica intrapleural.",
    "La farmacovigilancia sérica terapéutica de vancomicina previene la toxicidad tubulointersticial renal ajustando la posología a concentraciones valle específicas.",
    "El trasplante hepático ortotópico con donante cadavérico proporciona sobrevida prolongada en pacientes con cirrosis descompensada o falla hepática aguda.",
    "La biopsia de arteria temporal revela panarteritis granulomatosa transmural con infiltrado linfohistiocitario en la arteritis craneal de Horton.",
    "El bloqueo de la placa motora neuromuscular con bromuro de rocuronio asegura relajación muscular óptima durante intervenciones quirúrgicas laparoscópicas complejas.",
    "La inmunooncología con anticuerpos monoclonales anti-PD-1 potencia la citotoxicidad de linfocitos CD8 reactivos contra antígenos tumorales mutados.",
    "La tomografía por emisión de positrones integrada evalúa con máxima exactitud la estadificación nodular ganglionar regional de neoplasias malignas sólidas.",
    "La fibrobroncoscopia flexible diagnóstica con cepillado bronquial y lavado alveolar confirma etiologías infecciosas oportunistas en neumonías complejas.",
    "La anticoagulación preventiva con inhibidores directos del factor diez activado disminuye accidentes cerebrovasculares embólicos en fibrilación auricular persistente.",
    "La administración intramuscular de betametasona antenatal estimula la síntesis de surfactante pulmonar alveolar en gestaciones con amenaza de parto prematuro.",
    "La descompresión laminectómica descompresiva emergente previene parálisis vesical y déficits motores permanentes en el síndrome de cola de caballo agudo.",
    "La hipercalemia extrema con ensanchamiento del complejo QRS exige infusión intravenosa rápida de gluconato cálcico estabilizador miocárdico directo.",
    "La punción biopsia renal percutánea precisa el patrón glomerulonefrítico proliferativo o membranoso orientando protocolos terapéuticos inmunosupresores agresivos.",
    "El implante endocavitario de marcapasos bicameral definitivo erradica las pausas sinusales patológicas y las crisis sincopales de Stokes-Adams.",
    "El desbridamiento quirúrgico precoz y radical de fascias necróticas infectadas constituye el pilar terapéutico insustituible en fascitis necrotizante bacteriana.",
    "El dosaje sérico cuantitativo de procalcitonina guía la interrupción prudente de esquemas antibacterianos en sepsis bacteriana grave hospitalaria.",
    "La infusión parenteral de nitroprusiato sódico ejerce vasodilatación arteriovenosa equilibrada inmediata para controlar crisis hipertensivas con edema agudo pulmonar.",
    "La gastrostomía endoscópica percutánea provee vía nutricional enteral segura y duradera en pacientes con disfagia orofaríngea por daño encefálico.",
    "El abordaje terapéutico del dolor crónico oncológico terminal requiere analgesia escalonada con agonistas opioides mayores y coadyuvantes neuromoduladores específicos.",
    "El cateterismo cardíaco derecho con catéter arterial flotante evalúa la hipertensión precapilar cuantificando las resistencias vasculares pulmonares totales.",
    "La antibioticoterapia profiláctica intravenosa administrada treinta minutos antes de iniciar la incisión quirúrgica previene la sepsis de sitio operatorio.",
    "La plasmaféresis de recambio terapéutico depura complejos inmunes y anticuerpos IgG patógenos circulantes en crisis miasténicas y síndrome desmielinizante.",
    "La determinación del aclaramiento de creatinina en orina de veinticuatro horas proporciona un cálculo analítico validado de filtración glomerular.",
    "La termoablación percutánea por radiofrecuencia induce coagulación térmica focalizada en hepatocarcinomas unifocales menores a tres centímetros de diámetro.",
]

MEDICINA_CLAUSES_EN = [
    "Intravenous recombinant alteplase administration achieves rapid pharmacological thrombolysis and markedly enhances long-term functional neurological outcomes following ischemic cerebral infarction.",
    "Systematic differential diagnosis for acute abdominal emergencies in geriatric patients warrants urgent contrast-enhanced abdominopelvic computed tomography to confirm mesenteric vascular ischemia.",
    "Pharmacokinetic disposition of liposomal amphotericin formulations demonstrates significantly reduced renal accumulation, conferring superior nephrotoxic safety margins in invasive candidiasis.",
    "Diabetic ketoacidosis resuscitation requires prompt intravenous infusion of balanced electrolyte crystalloids, steady regular insulin administration, and rigorous serum potassium titration.",
    "Surgical reconstructive bypass grafting across obstructed peripheral arteries restores vital arterial perfusion and effectively relieves disabling intermittent limb claudication symptoms.",
    "Chronic congestive cardiomyopathy characterized by severely depressed ventricular systolic performance requires neurohormonal blockade incorporating mineralocorticoid receptor antagonists and gliflozin therapies.",
    "Septic shock resuscitation protocols prioritize prompt empiric antimicrobial infusion alongside norepinephrine vasopressor therapy targeting physiological mean arterial pressure benchmarks.",
    "Percutaneous ultrasound-guided core needle biopsy retrieves organized histological tissue ribbons suitable for immunohistochemical profiling of aggressive malignant mammary carcinomas.",
    "Urgent flexible gastrointestinal endoscopy reliably pinpoints bleeding mucosal ulcerations, enabling immediate deployment of dual endoscopic hemoclip and epinephrine therapies.",
    "Serial quantitative cardiac troponin assays establish acute cardiomyocyte injury thresholds, accelerating risk stratification for prospective acute coronary syndrome patients.",
    "Allogeneic hematopoietic stem cell engraftment offers potential curative remissions for high-risk myeloid hematological neoplasias refractory to induction regimens.",
    "Lung-protective invasive ventilator strategies employing low physiological tidal volumes attenuate mechanical barotrauma in acute respiratory distress syndrome.",
    "Intermittent extracorporeal hemodialysis removes toxic nitrogenous solutes and corrects marked electrolyte imbalances in chronic end-stage kidney failure.",
    "Severe hypertensive preeclampsia clinical management necessitates neuroprotective magnesium sulfate infusions alongside prompt labetalol administration to mitigate eclamptic seizure hazards.",
    "Adjuvant systemic chemotherapy incorporating cisplatin doublets markedly reduces distant relapse risk and improves overall survival following curative lung resection.",
    "Ultrasound-directed fine-needle aspiration of suspicious thyroid nodules enables standardized cytological categorization according to established Bethesda reporting guidelines.",
    "Monoclonal antibody neutralization targeting tumor necrosis factor alpha suppresses persistent chronic synovitis and progressive articular destruction in rheumatoid disease.",
    "Endovascular catheter thrombectomy achieves complete arterial recanalization, substantially reducing persistent neurological disability in proximal intracranial anterior circulation occlusions.",
    "Invasive monitoring of intracranial cerebrospinal pressures guides targeted hyperosmolar therapy to mitigate fatal brain herniation following severe contusional trauma.",
    "Empiric antimicrobial coverage for severe community-acquired pulmonary consolidation incorporates broad-spectrum beta-lactam bactericidal agents combined with advanced respiratory quinolones.",
    "Elevated circulating antinuclear antibody and anti-double-stranded DNA titers confirm underlying systemic lupus erythematosus in patients with multisystem clinical involvement.",
    "Laparoscopic surgical extirpation of the gallbladder remains the definitive operative approach for recurrent acute calculous biliary cholecystitis.",
    "Transthoracic echocardiographic examinations quantify anatomical aortic valvular stenosis severity by calculating transvalvular jet gradients and functional orifice dimensions.",
    "Synthetic sodium levothyroxine hormonal replacement therapy completely normalizes aberrant pituitary thyroid-stimulating hormone concentrations in symptomatic primary autoimmune hypothyroidism.",
    "Urgent surgical exploratory laparotomy remains imperative for septic peritoneal peritonitis secondary to acute perforated gastrointestinal hollow viscus lesions.",
    "Cardiogenic circulatory collapse involves critical forward ejection volume deficits resulting in widespread tissue hypoxia despite adequate ventricular diastolic filling.",
    "Elective endoscopic elastic band ligation represents established primary prophylactic therapy against catastrophic gastrointestinal bleeding from enlarged esophageal varices.",
    "Multicolor flow cytometric immunophenotyping identifies aberrant antigen expression patterns necessary for accurate lineage classification of acute undifferentiated leukemias.",
    "Dihydropyridine calcium channel antagonizing medications decrease peripheral arterial tonus through smooth muscle relaxation, effectively treating essential systemic vascular hypertension.",
    "Contrast-enhanced cranial magnetic resonance neuroimaging reveals distinctive periventricular white matter demyelinating plaques characteristic of relapsing-remitting multiple sclerosis.",
    "Vigorous early intravenous volume replacement utilizing balanced Hartmann solutions preserves microvascular perfusion, preventing necrotizing complications in acute biliary pancreatitis.",
    "Tube thoracostomy intercostal tube placement evacuated pneumothorax tension, instantly re-establishing negative intrapleural vacuum mechanics and pulmonary aeration.",
    "Therapeutic drug monitoring of vancomycin trough concentrations guides individualized dosage titrations, averting nephrotoxicity while assuring bactericidal pharmacodynamic efficacy.",
    "Orthotopic deceased-donor liver transplantation provides long-term survival for candidates suffering end-stage cirrhosis complicated by refractory portal hypertension.",
    "Histopathological confirmation of temporal Horton arteritis demonstrates transmural mononuclear inflammatory infiltrates with multinucleated giant cells destroying arterial elastic laminae.",
    "Nondepolarizing neuromuscular blocking drugs provide profound muscle flaccidity, facilitating atraumatic endotracheal intubation during extensive reconstructive abdominal surgical operations.",
    "Immune checkpoint blockade using anti-PD-1 monoclonal antibodies reinvigorates tumor-infiltrating cytotoxic T lymphocytes against resistant metastatic melanoma neoplastic antigens.",
    "Positron emission computerized imaging accurately pinpoints hypermetabolic regional lymphatic involvement and occult metastases in advanced systemic oncological presentations.",
    "Diagnostic video-assisted flexible bronchoscopy enables transbronchial parenchymal sampling and cytologic washings in immunocompromised individuals presenting diffuse interstitial infiltrates.",
    "Direct factor Xa inhibitory anticoagulants provide reliable stroke prevention without requiring frequent coagulation monitoring in nonvalvular chronic atrial fibrillation.",
    "Antenatal intramuscular glucocorticoid therapy significantly stimulates pulmonary surfactant synthesis, mitigating neonatal hyaline membrane respiratory distress incidence.",
    "Emergent surgical decompressive spine surgery averts irreversible sensorimotor loss and permanent paraplegia in traumatic acute cauda equina compression.",
    "Electrocardiographic signs of lethal hyperkalemia dictate emergency intravenous calcium infusion to stabilize cardiomyocyte excitable membranes against dysrhythmias.",
    "Percutaneous renal biopsy provides indispensable histological grading of proliferative glomerulonephritis, directing aggressive targeted corticosteroid immunosuppressive protocols.",
    "Transvenous permanent dual-chamber cardiac pacemaker implantation permanently eliminates life-threatening syncopal episodes in symptomatic high-grade atrioventricular heart blocks.",
    "Early radical operative excision of devitalized cutaneous tissues constitutes mandatory life-saving therapy in acute bacterial necrotizing soft tissue fasciitis.",
    "Serial quantitative serum procalcitonin determinations facilitate rational antimicrobial de-escalation decisions in critically ill septic intensive care patients.",
    "Continuous parenteral sodium nitroprusside titrations induce balanced arterial vasodilatation, promptly relieving acute hypertensive pulmonary hydrostatic capillary edema.",
    "Percutaneous endoscopic gastrostomy placement secures permanent enteral caloric delivery access in patients experiencing neurogenic pharyngeal dysphagia.",
    "Multimodal oncological palliative analgesia utilizes titrated sustained-release opioid analgesics coupled with adjuvant gabapentinoids for debilitating neuropathic cancer pain.",
    "Swan-Ganz catheterization accurately quantifies pulmonary artery wedge hemodynamics, facilitating hemodynamic differentiation of precapillary from postcapillary pulmonary vascular hypertension.",
    "Preoperative prophylactic intravenous cephalosporin administration administered half an hour prior to surgical skin incision reduces subsequent postoperative surgical infection.",
    "Therapeutic plasma exchange physically washes out pathogenic circulating anti-acetylcholine receptor autoantibodies in acute life-threatening myasthenic crises.",
    "Quantitative twenty-four-hour urinary creatinine clearance measurements yield an accurate physiological appraisal of filtration kinetics in progressive renal impairment.",
    "Percutaneous radiofrequency probe ablation induces complete coagulative thermal necrosis of solitary small focal hepatocellular carcinomas in non-surgical patients.",
]

# -----------------------------------------------------------------------------
# ASTRONOMIA (Astrofísica, mecánica orbital y cosmología)
# -----------------------------------------------------------------------------
ASTRONOMIA_CLAUSES_ES = [
    "La espectroscopía de alta resolución determina la abundancia química de elementos pesados en la fotosfera de gigantes rojas.",
    "El colapso gravitacional de núcleos estelares masivos que superan el límite de Chandrasekhar origina estrellas de neutrones densas.",
    "La detección de velocidades radiales periódicas mediante espectrógrafos estables evidencia la atracción gravitatoria ejercida por exoplanetas invisibles.",
    "La radiación cósmica de fondo de microondas muestra fluctuaciones térmicas primordiales que revelan la geometría plana del cosmos.",
    "La teoría general de la relatividad predice la curvatura geodésica del espacio-tiempo en las proximidades del horizonte de sucesos.",
    "La paralaje trigonométrica anual medida por telescopios espaciales proporciona distancias estelares geométricas libres de modelos astrofísicos.",
    "La fotometría de tránsitos planetarios mide la disminución fraccional del brillo estelar cuando el planeta cruza el disco celeste.",
    "La nucleosíntesis estelar primordial sintetizó helio y litio durante los primeros minutos de la expansión térmica del universo.",
    "La explosión cataclísmica de una supernova termonuclear de tipo uno a proporciona candelas estándar para medir distancias cosmológicas.",
    "La coalescencia de dos estrellas de neutrones emite ondas gravitacionales precursoras y contrapartes electromagnéticas de tipo kilonova.",
    "El corrimiento al rojo cosmológico de galaxias distantes se produce por la expansión métrica del propio tejido espacial interestelar.",
    "Las leyes keplerianas de la mecánica orbital describen con exactitud trayectorias elípticas de asteroides y cometas alrededor del Sol.",
    "La luminosidad estelar absoluta depende de la cuarta potencia de la temperatura superficial según la ley física de Stefan-Boltzmann.",
    "Los chorros relativistas colimados emergen a velocidades cercanas a la luz desde el disco de acreción del quasar.",
    "La fotoionización del gas nebular interestelar por radiación ultravioleta extrema genera líneas espectrales de emisión de hidrógeno.",
    "La curva de rotación plana en galaxias espirales constituye evidencia empírica directa de la presencia de halos de materia oscura.",
    "La precesión anómala del perihelio de Mercurio confirmó por primera vez las correcciones relativistas a la gravitación newtoniana.",
    "El colapso de nubes moleculares interestelares gigantes conduce a la fragmentación térmica y al nacimiento de cúmulos estelares.",
    "El diagrama de Hertzsprung-Russell correlaciona la luminosidad de las estrellas con su temperatura superficial en la secuencia principal.",
    "Las resonancias de movimientos medios entre satélites jovianos generan calor interno por mareas gravitatorias periódicas en Europa.",
    "Las lentes gravitacionales fuertes desvían la trayectoria luminosa produciendo imágenes múltiples y arcos de galaxias de fondo.",
    "La aceleración centrípeta orbital mantiene a los satélites artificiales en trayectorias geoestacionarias sincronizadas con la rotación terrestre.",
    "La pérdida de masa por vientos estelares intensos modula la evolución final de estrellas masivas de tipo Wolf-Rayet.",
    "La dispersión de velocidades en cúmulos galácticos masivos permite estimar la masa gravitacional total mediante el teorema del virial.",
    "La recombinación primordial de electrones y protones desacopló la radiación de la materia cuando el universo se enfrió suficientemente.",
    "La fotometría infrarroja de estrellas variables cefeidas calibra la escala de distancias extragalácticas mediante su relación período-luminosidad.",
    "La polarización de la radiación cósmica de fondo revela modos de tensión inducidos por ondas gravitacionales primordiales cosmológicas.",
    "La magnetohidrodinámica estelar gobierna la formación de manchas magnéticas y erupciones energéticas en la corona solar caliente.",
    "La eyección de envolturas gaseosas en estrellas de masa intermedia genera nebulosas planetarias con una enana blanca residual.",
    "La acreción de materia sobre una enana blanca en sistemas binarios compactos puede desencadenar una nova recurrente explosiva.",
    "El efecto Sunyaev-Zel'dovich dispersa fotones cósmicos al interactuar con el plasma electrónico caliente del gas intracúmulo galáctico.",
    "La interferometría de muy larga base sintetiza aperturas gigantescas para resolver la silueta oscura de agujeros negros supermasivos.",
    "La presión de degeneración electrónica sostiene a las enanas blancas frente al colapso gravitatorio originado por su propia masa.",
    "Las perturbaciones seculares en los elementos orbitales de planetas extrasolares evidencian la interacción gravitatoria mutua entre cuerpos celestes.",
    "La velocidad de escape de un objeto astronómico compacto depende directamente de su masa y del radio de su superficie.",
    "La nucleosíntesis por captura neutrónica rápida en fusiones estelares crea elementos pesados como oro, platino y uranio.",
    "El límite de Roche delimita la distancia mínima en la que un satélite celeste orbita sin ser disgregado por mareas.",
    "La radiación sincrotrón generada por electrones relativistas en campos magnéticos intensos delinea los lóbulos de radiogalaxias gigantes.",
    "La oscilación acústica de bariones imprinted en la distribución galáctica a gran escala actúa como una regla cósmica estándar.",
    "La velocidad orbital circular disminuye con la distancia radial al centro de atracción gravitatoria según la dinámica orbital.",
    "El arrastre inercial del espacio-tiempo predicho por Lense-Thirring afecta a giroscopios en órbita alrededor de cuerpos astronómicos giratorios.",
    "La fotodisociación molecular provocada por radiación interestelar dura confina el polvo cósmico a las regiones densas opacas.",
    "La tasa de formación estelar en galaxias con brote estelar excede ampliamente el ritmo de consumo típico del gas interestelar.",
    "La absorción interestelar provocada por granos de polvo submicrónicos enrojece y atenúa la luz de estrellas galácticas lejanas.",
    "La determinación de órbitas de estrellas próximas al centro galáctico confirma la masa concentrada del agujero negro supermasivo.",
    "La emisión de máseres astronómicos de vapor de agua traza el movimiento orbital en discos protoplanetarios densos en rotación.",
    "La inclinación orbital y la excentricidad determinan la insolación solar recibida y los ciclos climáticos astronómicos planetarios de Milankovitch.",
    "La presión de radiación estelar frena la acumulación gaseosa sobre protoestrellas masivas limitando su masa final máxima alcanzable.",
    "El efecto Doppler relativista modifica la intensidad luminosa percibida de chorros astrofísicos que apuntan hacia el observador terrestre.",
    "La masa de Jeans define el umbral crítico por encima del cual una nube molecular colapsa gravitatoriamente de forma inevitable.",
    "Las estrellas de población dos presentan bajas metalicidades reflejando la composición primordial del gas galáctico en épocas tempranas.",
    "La rotación diferencial de la zona convectiva solar amplifica los campos magnéticos toroidales mediante un mecanismo de dinamo astrofísica.",
    "La detección de púlsares de milisegundos proporciona relojes cósmicos de precisión extrema para sondear el fondo estocástico gravitacional.",
    "La dispersión cromática de señales de radio interestelares revela la densidad columnar de electrones libres en el medio interestelar.",
    "El horizonte cosmológico de partículas delimita la región máxima del espacio desde la cual la luz ha alcanzado la Tierra.",
]

ASTRONOMIA_CLAUSES_EN = [
    "High-resolution stellar spectroscopy accurately measures atmospheric chemical abundances and isotopic ratios within distant asymptotic giant branch stars.",
    "Gravitational collapse of degenerate stellar cores exceeding the Chandrasekhar mass limit triggers catastrophic thermonuclear or core-collapse supernova detonations.",
    "Periodic Doppler radial velocity shifts observed in stellar spectra confirm the gravitational perturbation exerted by orbiting sub-stellar exoplanetary companions.",
    "The cosmic microwave background radiation preserves primordial temperature anisotropies that establish the spatial flatness of the observable cosmological universe.",
    "General relativistic spacetime curvature dictates the geodesic trajectories of photons grazing the photon sphere surrounding rotating Kerr black holes.",
    "Precision trigonometric parallax measurements obtained by astrometric space observatories calibrate the fundamental galactic distance ladder without empirical assumptions.",
    "Transit photometry determines exoplanetary orbital inclination and planetary radius by detecting periodic fractional dips in host stellar flux.",
    "Primordial Big Bang nucleosynthesis produced light element isotopes during the initial relativistic expansion phase of the early universe.",
    "Thermonuclear type one a supernovae exhibit uniform peak absolute magnitudes, providing essential cosmological standard candles for dark energy measurements.",
    "Gravitational radiation emitted during binary neutron star inspiral precedes luminous electromagnetic kilonova emissions powered by radioactive heavy element decay.",
    "Cosmological redshift observed in extragalactic spectra results directly from the metric expansion of spacetime stretching propagating electromagnetic wavelengths.",
    "Keplerian orbital dynamics accurately predict orbital periods and semi-major axes for gravitational two-body systems throughout the solar neighborhood.",
    "Bolometric stellar luminosity scales with the fourth power of effective surface temperature according to the Stefan-Boltzmann radiation law.",
    "Relativistic astrophysical plasma jets emerge along rotation axes from magnetized accretion disks surrounding supermassive active galactic nucleus black holes.",
    "Ultraviolet photoionization of interstellar neutral hydrogen gas generates prominent Balmer recombination emission lines across star-forming emission nebulae.",
    "Flat galactic rotational velocity curves observed at large galactocentric radii provide compelling dynamical evidence for extended non-baryonic dark matter halos.",
    "Anomalous perihelion precession of planetary orbits provided the earliest empirical confirmation of post-Newtonian relativistic gravitational field equations.",
    "Gravitational fragmentation of dense giant molecular clouds initiates protostellar core collapse and subsequent formation of bound stellar clusters.",
    "The Hertzsprung-Russell diagram organizes stellar luminosity against effective spectral temperature, delineating clear evolutionary sequences for stellar populations.",
    "Mean motion orbital resonances among Jovian satellites induce cyclic tidal dissipation that sustains internal subsurface oceanic heating on Europa.",
    "Strong gravitational lensing by massive galaxy clusters magnifies and distorts background galaxies into elongated luminous giant arcs.",
    "Orbital velocity along circular Keplerian trajectories decreases monotonically with increasing orbital radius around the central gravitational mass.",
    "Radiative wind mass loss rates significantly alter stellar evolutionary trajectories in luminous blue variables and massive Wolf-Rayet stars.",
    "Velocity dispersion measurements of galaxies residing within massive virialized clusters constrain total gravitational cluster mass via the virial theorem.",
    "Cosmological recombination decoupled primeval photons from baryonic matter as cooling plasma allowed stable neutral hydrogen formation.",
    "Infrared photometry of Classical Cepheid pulsating variables calibrates extragalactic distances through well-defined empirical period-luminosity relations.",
    "Primordial B-mode cosmic microwave background polarization patterns carry signatures of relic tensor perturbations generated during early cosmic inflation.",
    "Magnetohydrodynamic dynamos operating within stellar convective zones generate intense toroidal magnetic fields that drive violent coronal mass ejections.",
    "Planetary nebulae represent expanding circumstellar shells of ionized gas ejected during asymptotic giant branch thermal pulses, exposing white dwarfs.",
    "Cataclysmic variable systems transfer matter via accretion streams toward degenerate white dwarfs, occasionally triggering explosive runaway thermonuclear novae.",
    "The thermal Sunyaev-Zel'dovich effect distorts cosmic microwave background spectra through inverse Compton scattering off hot intra-cluster gas electrons.",
    "Very-long-baseline radio interferometry achieves micro-arcsecond angular resolution, reconstructing shadowed event horizons of supermassive black holes.",
    "Quantum electron degeneracy pressure prevents further gravitational contraction in cooling white dwarf stars beneath the Chandrasekhar limiting mass.",
    "Secular planetary orbital perturbations produce cyclic variations in orbital eccentricity and orbital inclination over million-year astronomical timescales.",
    "Gravitational escape velocity from compact astronomical bodies depends strictly upon enclosed mass and exterior radial surface distance.",
    "Rapid neutron-capture nucleosynthesis occurring within binary compact merger ejecta synthesizes heavy actinide and lanthanide elements.",
    "The astronomical Roche limit defines the critical distance inside which tidal forces overcome self-gravitational cohesion, destroying orbiting bodies.",
    "Relativistic synchrotron radiation produced by ultra-relativistic electrons gyrating in magnetic fields illuminates extended radio galaxy lobes.",
    "Baryon acoustic oscillations imprinted onto large-scale galactic spatial distributions serve as cosmological standard rulers measuring expansion history.",
    "Orbital transfer maneuvers between coplanar circular orbits utilize elliptical Hohmann trajectories to minimize required orbital propellant expenditure.",
    "Frame dragging induced by rotating astronomical masses perturbs the orientation of orbiting gyroscopes via the gravitomagnetic Lense-Thirring effect.",
    "Far-ultraviolet photodissociation regions govern the thermal equilibrium and chemistry between diffuse interstellar gas and dense molecular clouds.",
    "Starburst galaxies exhibit extraordinarily high star formation rates that deplete available cold molecular gas reservoirs on rapid astronomical timescales.",
    "Interstellar dust grain scattering causes wavelength-dependent interstellar extinction, reddening observed optical spectra of distant galactic stars.",
    "Precise astrometric orbital tracking of stars surrounding the galactic center confirms the existence of a four-million-solar-mass supermassive black hole.",
    "Circumnuclear water megamaser emissions trace Keplerian rotation in thin accretion disks, yielding direct geometric distances to active galaxies.",
    "Milankovitch orbital cycles alter seasonal solar irradiance distributions across planetary hemispheres, driving long-term astronomical paleoclimatic shifts.",
    "Stellar radiation pressure on dust grains expels circumstellar envelopes around luminous protostars, setting an upper limit to stellar masses.",
    "Relativistic Doppler beaming dramatically enhances observed flux from relativistic astrophysical jets oriented toward the observer line of sight.",
    "The classical Jeans mass threshold dictates when internal gas thermal pressure fails to balance inward gravitational forces within molecular clouds.",
    "Low-metallicity Population Two halo stars preserve chemical fingerprints reflecting early galactic nucleosynthetic enrichment by primordial hypernovae.",
    "Differential rotation across the solar interior tachocline shears poloidal magnetic field lines, driving the cyclic eleven-year solar dynamo.",
    "High-precision millisecond pulsar timing arrays monitor subtle pulse arrival variations to detect stochastic nanohertz gravitational wave backgrounds.",
    "Frequency-dependent chromatic dispersion of astrophysical radio pulses measures line-of-sight free electron column densities across interstellar space.",
    "The particle cosmological horizon demarcates the boundary of the observable universe from which photons have had time to reach Earth.",
]


def assemble_deck(alma: str, clauses_es: list[str], clauses_en: list[str]) -> dict:
    clauses = []
    idx = 1
    for text in clauses_es:
        clauses.append(
            {
                "id": f"{alma}-es-{idx:03d}",
                "text": text,
                "lang": "es",
                "source": f"corpus-extendido-{alma}",
            }
        )
        idx += 1

    idx = 1
    for text in clauses_en:
        clauses.append(
            {
                "id": f"{alma}-en-{idx:03d}",
                "text": text,
                "lang": "en",
                "source": f"corpus-extendido-{alma}",
            }
        )
        idx += 1

    return {
        "alma": alma,
        "n": len(clauses),
        "description": f"Mazo extendido de {alma} con balance bilingue (ES/EN) de alta densidad terminologica.",
        "clauses": clauses,
    }


def main():
    decks = {
        "receta": assemble_deck("receta", RECETA_CLAUSES_ES, RECETA_CLAUSES_EN),
        "python": assemble_deck("python", PYTHON_CLAUSES_ES, PYTHON_CLAUSES_EN),
        "legal": assemble_deck("legal", LEGAL_CLAUSES_ES, LEGAL_CLAUSES_EN),
        "medicina": assemble_deck("medicina", MEDICINA_CLAUSES_ES, MEDICINA_CLAUSES_EN),
        "astronomia": assemble_deck("astronomia", ASTRONOMIA_CLAUSES_ES, ASTRONOMIA_CLAUSES_EN),
    }

    for alma, deck in decks.items():
        out_path = OUT_DIR / f"{alma}.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(deck, f, indent=2, ensure_ascii=False)
        print(f"Generado {out_path} ({deck['n']} cláusulas)")


if __name__ == "__main__":
    main()
